version: '3.7'

services:
  codypaste_service:
    build: .
    environment:
      BASE_APP_URL: 'localhost:8080'
      PG_HOST: 'postgres'
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: codypaste-develop
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  postgres: